### ISSUE TITLE
Make default viridis

### ISSUE THREAD

**Issue by rmflight** [bhaskarvk/colormap#3]
Instead of having jet be the default, as one of the worst perceptual maps in existence, could the default be viridis or one based on it?? I think we should be doing all we can to discourage the use of jet as a color map.

**Comment by bhaskarvk** [comment]
I fixed in trunk, but will wait for a few days to push to CRAN, as CRAN discourages frequent updates.

**Comment by rmflight** [comment]
Understand that. Thanks for taking the suggestion!
